config_map:
  - name: PRODUCT
    value: "{{ product.name }}"    
  - name: PRODUCT_DESCRIPTION
    value: "{{ product.description }}"    
  - name: TASK_MANAGEMENT_TITLE
    value: "{{ task_manager.title }}"
  - name: GATEWAY_API_SERVICE_URI
    value: "http://console-gateway-api-{{ project }}.{{ openshift.subdomain }}" 