name: CI Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - name: Install node packages from registry
      run: yarn install --frozen-lockfile

    - name: Run the tests
      run: yarn test:ci

    - name: Build the project
      run: yarn build
      env:
        PRODUCT_DESCRIPTION: Example product description
        GATEWAY_API_SERVICE_URI: https://example.api
