name: CI Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install node packages from registry
      run: npm ci

    - name: Run the tests
      run: npm run test:ci

    - name: Build the project
      run: npm run build
