name: CI Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install node packages from registry
      run: npm ci

    - name: Build the project
      run: npm run build

    - name: Run the tests
      run: npm run test:ci
