name: CI Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1

      - name: Run the linter
        run: yarn lint

      - name: Run the tests
        run: yarn test:ci

      - name: Build the project
        run: yarn build
