name: CI Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install node packages from registry
      run: yarn install --frozen-lockfile
      env:
        # Skip the post install script used to build the app in OpenShift
        NO_POST_INSTALL: true

    - name: Run the tests
      run: yarn test:ci

    - name: Build the project
      run: yarn build
